version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: ${PROJECT_NAME}
    env_file:
      - .env
    ports:
      - "8000:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
